# Copyright (c) 2019 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: python

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      sudo: required
      python: "3.6"
      before_install:
        - openssl aes-256-cbc -K $encrypted_94fb5708c762_key -iv $encrypted_94fb5708c762_iv -in Credential.enc -out Aljuaritmo-3ac32e58ff41.json -d
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - ${HOME}/.conan
          - ${TRAVIS_BUILD_DIR}/cmakebin
      after_success:
        - codecov -F Linux -X gcov
    - os: osx
      osx_image: xcode9.3
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.6.5
      before_install:
        - openssl aes-256-cbc -K $encrypted_94fb5708c762_key -iv $encrypted_94fb5708c762_iv -in Credential.enc -out Aljuaritmo-3ac32e58ff41.json -d
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - $HOME/.pyenv
          - $HOME/Library/Caches/Homebrew
          - ${HOME}/.conan
      after_success:
        - codecov -F MacOS -X gcov
install:
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-khiva.sh
  - source .CI/travis/install.sh

script:
  - source .CI/travis/build_and_test.sh